openapi: 3.0.0
info:
  title: Concordance
  description: A simple concordance API.
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/csumano/Concordance/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: analysis
  description: Operations available for text analysis
paths:
  /analyze:
    post:
      tags:
      - analysis
      summary: Calculate
      description: Post text to generate concordance
      operationId: get_concordance
      requestBody:
        description: Text to be analyzed
        content:
          text/plain:
            schema:
              type: string
            example: The brown fox jumped over the brown log.
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/result'
        "400":
          description: invalid input, object invalid
      x-openapi-router-controller: swagger_server.controllers.analysis_controller
  /locate:
    post:
      tags:
      - analysis
      summary: Calculate and locate
      description: Post text to generate concordance and location
      operationId: get_concordance_v2
      requestBody:
        description: Text to be analyzed and located
        content:
          text/plain:
            schema:
              type: string
            example: The brown fox jumped over the brown log.
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/result2'
        "400":
          description: invalid input, object invalid
      x-openapi-router-controller: swagger_server.controllers.analysis_controller
components:
  schemas:
    result:
      required:
      - concordance
      - input
      type: object
      properties:
        concordance:
          type: array
          example:
          - token: brown
            count: 2
          - token: fox
            count: 1
          - token: jumped
            count: 1
          - token: log
            count: 1
          - token: over
            count: 1
          - token: the
            count: 1
          items:
            $ref: '#/components/schemas/result_concordance'
        input:
          type: string
          example: The brown fox jumped over the brown log.
      example:
        input: The brown fox jumped over the brown log.
        concordance:
        - token: brown
          count: 2
        - token: fox
          count: 1
        - token: jumped
          count: 1
        - token: log
          count: 1
        - token: over
          count: 1
        - token: the
          count: 1
    result2:
      required:
      - concordance
      - input
      type: object
      properties:
        concordance:
          type: array
          example:
          - token: brown
            locations:
            - 1
            - 5
          - token: fox
            locations:
            - 2
          - token: jumped
            locations:
            - 3
          - token: log
            locations:
            - 7
          - token: over
            locations:
            - 4
          - token: the
            locations:
            - 0
            - 5
          items:
            $ref: '#/components/schemas/result_concordance'
        input:
          type: string
          example: The brown fox jumped over the brown log.
      example:
        input: The brown fox jumped over the brown log.
        concordance:
        - token: brown
          locations:
          - 1
          - 5
        - token: fox
          locations:
          - 2
        - token: jumped
          locations:
          - 3
        - token: log
          locations:
          - 7
        - token: over
          locations:
          - 4
        - token: the
          locations:
          - 0
          - 5
    result_concordance:
      type: object
      properties:
        token:
          type: string
        count:
          type: integer

